import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { AppHeader, Card, Pill, Screen, SectionTitle, ui } from '@/components/karma-ui';
import { Palette } from '@/constants/theme';
import { usePrototype } from '@/context/prototype-context';

export default function LearnScreen() { const { courseProgress } = usePrototype(); return <Screen><AppHeader title="Learn" subtitle="Wisdom for everyday life" /><View><Text style={ui.title}>Continue learning</Text><Text style={ui.body}>Explore teachings, practices, and reflections at your own pace.</Text></View><Pressable onPress={() => router.push('/flows/course-detail' as any)}><Card style={styles.featured}><View style={styles.art}><Text style={styles.symbol}>◉</Text></View><Pill>IN PROGRESS</Pill><Text style={styles.title}>Foundations of mindful living</Text><Text style={ui.small}>{courseProgress}% complete · Lesson 3 of 6</Text><View style={styles.track}><View style={[styles.fill, { width: `${courseProgress}%` }]} /></View></Card></Pressable><SectionTitle>Explore courses</SectionTitle><View style={styles.list}>{['The art of self-inquiry', 'Bhagavad Gita: a gentle introduction', 'Living with compassion'].map((course, index) => <Pressable key={course} onPress={() => router.push('/flows/courses' as any)}><Card style={styles.course}><Text style={styles.number}>0{index + 1}</Text><View style={{ flex: 1, gap: 4 }}><Text style={styles.courseTitle}>{course}</Text><Text style={ui.small}>6 lessons · Beginner friendly</Text></View><Text style={styles.arrow}>›</Text></Card></Pressable>)}</View></Screen>; }
const styles = StyleSheet.create({ featured: { gap: 10 }, art: { height: 152, borderRadius: 20, backgroundColor: Palette.goldSoft, alignItems: 'center', justifyContent: 'center' }, symbol: { fontSize: 50, color: Palette.goldDark }, title: { color: Palette.charcoal, fontFamily: 'serif', fontSize: 23, fontWeight: '700' }, track: { height: 7, overflow: 'hidden', borderRadius: 8, backgroundColor: Palette.goldSoft }, fill: { height: '100%', borderRadius: 8, backgroundColor: Palette.gold }, list: { gap: 10 }, course: { paddingVertical: 15, flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 20 }, number: { color: Palette.goldDark, fontFamily: 'serif', fontSize: 22, fontWeight: '700' }, courseTitle: { color: Palette.charcoal, fontWeight: '700', fontSize: 16 }, arrow: { color: Palette.goldDark, fontSize: 28 } });
