import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { AppHeader, AppIcon, Card, KarmaLogo, Screen, SectionTitle, ui } from '@/components/karma-ui';
import { Palette } from '@/constants/theme';
import { useSession } from '@/context/auth-context';
import { usePrototype } from '@/context/prototype-context';

const links = [['Profile & preferences', 'profile', 'settings'], ['Mood & wellbeing', 'mood-insights', 'heart'], ['AI spiritual guide', 'guide', 'spark'], ['Achievements', 'achievements', 'check'], ['Activity history', 'activity-history', 'calendar'], ['Notifications', 'notifications', 'bell'], ['Device sessions', 'sessions', 'profile']];
export default function ProfileScreen() { const { user, signOut } = useSession(); const { completedTasks, courseProgress } = usePrototype(); const name = user?.name || user?.email?.split('@')[0] || 'Seeker'; return <Screen><AppHeader title="Profile" subtitle="Your personal sanctuary" /><Card style={styles.profile}><KarmaLogo size={72} /><View style={{ flex: 1, gap: 3 }}><Text style={styles.name}>{name}</Text><Text style={ui.small}>{user?.email || 'Your Karma Vajra journey'}</Text><Text style={styles.member}>Member since 2026</Text></View></Card><View style={styles.stats}><Stat number={`${completedTasks.length}/5`} label="Today’s practice" /><Stat number={`${courseProgress}%`} label="Learning" /><Stat number="7" label="Day streak" /></View><SectionTitle>Your journey</SectionTitle><View style={styles.list}>{links.map(([label, flow, icon]) => <Pressable key={flow} onPress={() => router.push(`/flows/${flow}` as any)}><Card style={styles.item}><AppIcon name={icon} active /><Text style={styles.itemText}>{label}</Text><Text style={styles.arrow}>›</Text></Card></Pressable>)}</View><Pressable onPress={signOut} style={styles.signOut}><Text style={styles.signOutText}>Sign out</Text></Pressable></Screen>; }
function Stat({ number, label }: { number: string; label: string }) { return <View style={styles.stat}><Text style={styles.statNumber}>{number}</Text><Text style={ui.small}>{label}</Text></View>; }
const styles = StyleSheet.create({ profile: { flexDirection: 'row', alignItems: 'center', gap: 15 }, name: { color: Palette.charcoal, fontFamily: 'serif', fontSize: 24, fontWeight: '700' }, member: { color: Palette.goldDark, fontSize: 12, fontWeight: '700' }, stats: { flexDirection: 'row', gap: 9 }, stat: { flex: 1, minHeight: 88, padding: 12, backgroundColor: Palette.surface, borderWidth: 1, borderColor: Palette.line, borderRadius: 18, gap: 5 }, statNumber: { color: Palette.charcoal, fontFamily: 'serif', fontSize: 20, fontWeight: '700' }, list: { gap: 10 }, item: { borderRadius: 20, paddingVertical: 15, flexDirection: 'row', alignItems: 'center', gap: 13 }, itemText: { flex: 1, color: Palette.charcoal, fontSize: 16, fontWeight: '700' }, arrow: { color: Palette.goldDark, fontSize: 28 }, signOut: { height: 52, borderRadius: 17, justifyContent: 'center', alignItems: 'center', backgroundColor: Palette.blush, marginTop: 5 }, signOutText: { color: Palette.danger, fontWeight: '800' } });
